### PR TITLE
add "closeOnSelect" option for "daytime" mode.

### PR DESCRIPTION
**Pull request by Rouhollah**
add "closeOnSelect" option for "daytime" mode.
for "daytimeDirective" and "daytime"

### CODE REVIEW

**Comment by fingerpich** [comment]
Hi,
sorry for delay
can you please also add a short description in Readme.md file.

Thanks.

**Comment by Rouhollah** [comment]
"daytime" added for closeOnSelect in Readme.md line 121.

**Comment by fingerpich** [comment]
Thanks

**Comment by fingerpich** [comment]
Can you also please run `npm run release`? does it work for you?

**Comment by Rouhollah** [comment]
on demo , it's worked. ng build passed. then i run:
`
D:\jalali-angular-datepicker\dist>npm run release

> ng2-jalali-date-picker@2.2.8 release D:\jalali-angular-datepicker
> npm run build:prod && npm publish bin


> ng2-jalali-date-picker@2.2.8 build:prod D:\jalali-angular-datepicker
> ng-packagr -p package.json && cp -R screenshots bin

Building Angular library
Generating bundle for ng2-jalali-date-picker
Cleaning bundle build directory
Processing assets
Running ngc
Compiling to FESM15
Compiling to FESM5
Compiling to UMD
Minifying UMD bundle
Dropping unreachable code [0:414,8]
Declarations in unreachable code! [0:414,8]
Remapping source maps
Copying staged files
Writing package metadata
Built Angular bundle for ng2-jalali-date-picker
Built Angular library from D:\jalali-angular-datepicker, written to bin
'cp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng2-jalali-date-picker@2.2.8 build:prod: `ng-packagr -p package.json && cp -R screenshots bin`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-jalali-date-picker@2.2.8 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\r.torshizi\AppData\Roaming\npm-cache\_logs\2021-05-23T11_37_16_439Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ng2-jalali-date-picker@2.2.8 release: `npm run build:prod && npm publish bin`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-jalali-date-picker@2.2.8 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\r.torshizi\AppData\Roaming\npm-cache\_logs\2021-05-23T11_37_16_474Z-debug.log`

**Comment by fingerpich** [comment]
So its working for you
Can you please send me an email (zarei.bs@gmail.com) to give you the user name and password. so you will be able to publish it to npm repository.

**Comment by Rouhollah** [comment]
sent.

**Pull request merged**
